nsc_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_joint4
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_joint5
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_joint6
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  wheel_front_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_wheel_front_right
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  wheel_front_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_wheel_front_left
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  lio_gripper_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lio_gripper_joint
    pid: { p: 100.0, i: 0.01, d: 10.0 }