nsc_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  wheel_front_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_wheel_front_right
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  wheel_front_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_wheel_front_left
    pid: { p: 100.0, i: 0.01, d: 10.0 }
