<?xml version="1.0"?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="nsc_robot_arm">
    <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass2" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width2" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height4" value="1" /> <!-- Link 1 -->
  <xacro:property name="height5" value="0.5" /> <!-- Link 2 -->
  <xacro:property name="height6" value="0.5" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

<xacro:macro name="arm" params="parent_link name_link height width x y z rot_x rot_y rot_z">
    <link name="${name_link}">

        <collision>
          <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
          <geometry>
        <box size="${width} ${width} ${height}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
          <geometry>
        <box size="${width} ${width} ${height}"/>
          </geometry>
          <material name="orange"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
          <mass value="${mass2}"/>
          <inertia
          ixx="${mass2 / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
          iyy="${mass2 / 12.0 * (height*height + width*width)}" iyz="0.0"
          izz="${mass2 / 12.0 * (width*width + width*width)}"/>
        </inertial>
      </link>

    <joint name="joint_${name_link}" type="continuous">
    <parent link="${parent_link}"/>
    <child link="${name_link}"/>
    <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    <axis xyz="${rot_x} ${rot_y} ${rot_z}"/>
    <dynamics damping="0.7"/>
  </joint>
</xacro:macro>

<xacro:arm parent_link="base_link" name_link="arm1" height="${height4}" width="${width2}" x="0" y="0" z="0.25" rot_x="0" rot_y="0" rot_z="1"/>
<xacro:arm parent_link="arm1" name_link="arm2" height="${height5}" width="${width2}" x="0" y="${width2}" z="${height4 - width2/2}" rot_x="0" rot_y="1" rot_z="0"/>
<xacro:arm parent_link="arm2" name_link="arm3" height="${height6}" width="${width2}" x="0" y="${width2}" z="${height5 - width2/2}" rot_x="0" rot_y="1" rot_z="0"/>
</robot>
